Made up registration page
jekasrs/online-pharmacy-client pull request #10
Opened 2023-11-06 00:06 UTC by mikhaillevashov

<img width="906" alt="Снимок экрана 2023-11-06 в 03 05 48" src="https://github.com/jekasrs/online-pharmacy-client/assets/108690016/48f4bb31-fb6b-4a42-9634-3804c43fd13f">

2023-11-06 10:45 UTC, jekasrs requested changes
Fix my comments. Do not push the same changes (in login page and registration page) twice. I mean I checked login-page.html/.css twice.

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/app.component.html
>  </body>
Смотри замечание review для login page

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.css
> +
Blank line

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.css
> +
Blank line

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +    <p class="text-general" style="padding-left: 200px; margin-bottom: 0; margin-top: 30px">Введите логин</p>
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +  <h1 style="margin: 0; margin-top: 30px">Авторизация</h1>
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +    <p class="text-general"  style="padding-left: 200px; margin-bottom: 0; margin-top: 30px">Введите пароль</p>
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +    <div style="padding-left: 160px">
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +    <button  class="button-color" style="width: 152px; height: 63px;">Вход</button>
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/registration-page/registration-page.component.html
> +  <h1 style="margin: 0; margin-top: 30px">Регистрация</h1>
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/registration-page/registration-page.component.html
> +      <button  class="button-color" style="width: 318px; height: 63px;">Зарегистрироваться</button>
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/registration-page/registration-page.component.html
> +    <div style="padding-left: 160px">
Style не пишем в html

2023-11-06 10:45 UTC, jekasrs commented on code/src/app/components/registration-page/registration-page.component.html
> +      <input type="text" class="text-general">
первый атрибут любого элемента должен быть class. ))))

2023-11-06 10:45 UTC, jekasrs commented on code/src/styles.css
> +  font-size: 44px;
Плохая идея

2023-11-06 10:45 UTC, jekasrs commented on code/src/styles.css
> +  font-size: 44px;
Обоснуй почему, а то так не понятно что и зачем.

2023-11-06 10:45 UTC, jekasrs commented on code/src/styles.css
>  /*Заголовки первого уровня*/
Комментарий супер! Удали его

2023-11-06 14:53 UTC, mikhaillevashov commented on code/src/styles.css
>  /*Заголовки первого уровня*/
Это не мой комментарий, а твой вообще

2023-11-06 14:54 UTC, mikhaillevashov commented on code/src/styles.css
> +  font-size: 44px;
Потому что у нас заголовки первого уровня везде 44px, а не 36px. Это надо всем поменять

2023-11-06 15:36 UTC, jekasrs commented on code/src/styles.css
>  /*Заголовки первого уровня*/
Проект общий, код общий, СССР

2023-11-13 20:59 UTC, Lysenko-Aleksandra commented on code/src/app/app.component.html
>  </body>
@jekasrs можно писать комментарии только на одном языке хотя бы в рамках одного MR?.....

2023-11-14 18:49 UTC, jekasrs approved these changes

2023-11-14 18:50 UTC, merged