Main page
jekasrs/online-pharmacy-client pull request #11
Opened 2023-11-07 19:22 UTC by maryshekk

2023-11-08 13:29 UTC, jekasrs requested changes
Fix all comments, please

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
Можешь сделать везде один вид открывающихся скобок... 
Пример: 

класс. {
    атрибут 1 
    ....
}

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.html
> +  <img src="../../../../assets/pictures/instead-of-photo-img.png">
Вроде .../.../.../ не нужны, можно сразу писать assets.

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/cart-page/cart-order-card/cart-order-card.component.css
> +}
Что это?

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/cart-page/cart-order-card/cart-order-card.component.html
> +        <label for="checkbox-id" class="text">
первый параметр во всех элементах class

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/cart-page/cart.component.css
> +
Пустота

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/cart-page/cart.component.css
> +.host
Разные скобочки опять

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/cart-page/cart.component.html
> +  <app-cart-item-card></app-cart-item-card>
Внутренние элементы на одном уровне с внешним

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/filter/filter.component.html
> +<!--  <p *ngIf="user.isAdmin||user.isDoctor">-->
Зачем эти комментарии?

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/header/header.component.css
Разный стиль скобочек

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/header/header.component.html
Первый атрибут элемента - "class"

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/main-page/item/item.component.html
> +  <img class="card img" src="../assets/pictures/instead-of-photo-img.png">
assets можно сразу писать, нет?

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/product-page/card-item/card-item.component.ts
> +// }
Ужас... 

Маша, не надо пушить эту страничку, пожалуйста.

2023-11-08 13:29 UTC, jekasrs commented on code/src/app/components/user-page/account/account.component.css
скобки

2023-11-09 12:22 UTC, maryshekk commented on code/src/app/components/cart-page/cart-order-card/cart-order-card.component.css
> +}
это настройка чекбокса, чтоб он был адекват красивый, а не та фигня, которая базово у чекбокса стоит

2023-11-10 19:03 UTC, jekasrs commented on code/src/app/components/filter/filter.component.html
> +<!--  <p *ngIf="user.isAdmin||user.isDoctor">-->
ok

2023-11-10 19:04 UTC, jekasrs commented on code/src/app/components/header/header.component.css
Хорошо

2023-11-10 19:05 UTC, jekasrs commented on code/src/app/components/header/header.component.html
Хорошо

2023-11-10 19:06 UTC, jekasrs approved these changes

2023-11-10 19:18 UTC, jekasrs commented
Static main page is done.

2023-11-10 19:19 UTC, merged