User page
jekasrs/online-pharmacy-client pull request #13
Opened 2023-11-09 14:54 UTC by maryshekk

![image](https://github.com/jekasrs/online-pharmacy-client/assets/106404275/23837cba-627c-44c1-bc97-a75e5d0014ee)

2023-11-10 19:40 UTC, jekasrs requested changes
Fix comments, please

2023-11-10 19:40 UTC, jekasrs commented on code/.gitignore
Надо решить проблему с разными гит игнорами у каждой ветки.

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +.text{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +.text.delete{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +.card.pricearea.quatity{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +.text.quatity{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-item-card/cart-item-card.component.css
> +.text.price{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart-order-card/cart-order-card.component.css
> +
Пустая строка

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart.component.css
> +{
Скобки

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart.component.css
> +
Пустота

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/cart-page/cart.component.html
> +  <app-cart-item-card></app-cart-item-card>
внутреннее элементы должны быть написаны на один отступ больше

2023-11-10 19:40 UTC, jekasrs commented on code/src/app/components/product-page/card-item/card-item.component.ts
> +// import { Component } from '@angular/core';
Удобно однако, проехали, изменю сам в своем пул реквесте

2023-11-13 20:53 UTC, Lysenko-Aleksandra commented
По названию MR должно быть понятно, что в его рамках было реализовано. 

Сейчас кажется, будто в рамках этого MR была реализована статическая страница личного кабинета пользователя. Однако, если начать смотреть код, то станет понятно, что в рамках MR реализовано форматирование стиля кода(добавлены/убраны пробелы).

В таком случае, MR стоило бы назвать **Fix style in User page (css)**

2023-11-13 21:17 UTC, Lysenko-Aleksandra commented
@jekasrs может быть, вам тоже сделать CI/CD хотя бы на форматирование кода?

2023-11-14 18:53 UTC, jekasrs approved these changes

2023-11-14 18:55 UTC, merged