Test header
jekasrs/online-pharmacy-client pull request #59
Opened 2024-02-15 20:24 UTC by maryshekk

tests for header, header-pharmacist, header-authorized and header-unauthorized components

2024-02-16 13:25 UTC, jekasrs requested changes
change name of the title

2024-02-16 13:25 UTC, jekasrs commented on code/src/app/app.component.spec.ts
> +  it(`should have as title 'Propill'`, () => {
ProPill

2024-02-16 13:25 UTC, jekasrs commented on code/src/app/app.component.spec.ts
> +    expect(compiled.querySelector('.content span')?.textContent).toContain('Propill');
ProPill

2024-02-17 13:48 UTC, mikhaillevashov approved these changes

2024-02-18 19:15 UTC, jekasrs approved these changes

2024-02-18 20:50 UTC, merged