Made up login page
jekasrs/online-pharmacy-client pull request #7
Opened 2023-11-05 20:45 UTC by mikhaillevashov

<img width="914" alt="Снимок экрана 2023-11-05 в 23 40 39" src="https://github.com/jekasrs/online-pharmacy-client/assets/108690016/6adaffb9-b389-4f6f-9756-1ab9e472d889">

2023-11-06 10:38 UTC, jekasrs requested changes
Fix my comments.

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/app.component.html
давайте не изменять каждый раз app.component... Оставим его **пустым** в develop ветки.

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.css
> +
blank line

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.css
> +
blank line

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +    <p class="text-general"  style="padding-left: 200px; margin-bottom: 0; margin-top: 30px">Введите пароль</p>
Style не пишем в html

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +  <h1 style="margin: 0; margin-top: 30px">Авторизация</h1>
Style не пишем в html

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +    <button  class="button-color" style="width: 152px; height: 63px;">Вход</button>
Style не пишем в html

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.html
> +    <div style="padding-left: 160px">
Style не пишем в html

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.ts
Зачем тебе нужно эти imports?

2023-11-06 10:38 UTC, jekasrs commented on code/src/app/components/login-page/login-page.component.ts
> +  }
copy past

2023-11-06 10:38 UTC, jekasrs commented on code/src/styles.css
>  /*Заголовки первого уровня*/
Комментарий излишний для h1

2023-11-06 10:38 UTC, jekasrs commented on code/src/styles.css
> +  font-size: 44px;
Плохая идея менять в глобальном файле стиль. Найди другой способ.

2023-11-06 14:56 UTC, mikhaillevashov commented on code/src/app/app.component.html
Хорошо

2023-11-06 14:57 UTC, mikhaillevashov commented on code/src/app/components/login-page/login-page.component.ts
Тут все будет доработано, пока что был сделан исключительно дизайн страницы

2023-11-06 14:57 UTC, mikhaillevashov commented on code/src/styles.css
>  /*Заголовки первого уровня*/
Ответ в registration-page

2023-11-06 14:57 UTC, mikhaillevashov commented on code/src/styles.css
> +  font-size: 44px;
Ответ в registration-page

2023-11-13 20:56 UTC, Lysenko-Aleksandra commented on code/src/styles.css
>  /*Заголовки первого уровня*/
@mikhaillevashov  можно делать ссылку на MR(это облегчит работу)
#10 это ссылка на registration page

2023-11-14 18:42 UTC, jekasrs approved these changes

2023-11-14 18:45 UTC, merged