Used BEM convention and made changes in design
jekasrs/online-pharmacy-client pull request #8
Opened 2023-11-05 23:13 UTC by jekasrs

Renamed all elements in product-card.css and .html, changed style properties in list, eligned elements, added in style.css hover for mouse.
<img width="1329" alt="Снимок экрана 2023-11-06 в 00 12 57" src="https://github.com/jekasrs/online-pharmacy-client/assets/90210620/7944d182-7547-4429-b876-a582e2501c3d">

2023-11-09 15:55 UTC, maryshekk requested changes

2023-11-09 15:55 UTC, maryshekk commented on code/src/app/components/product-card/product-card.component.css
>  }
не соблюден отступ слева для области, в которой располагается контент - он везде одинаковый, давай придерживаться едных правил верстки страницы

2023-11-09 15:55 UTC, maryshekk commented on code/src/styles.css
>    font-family: Raleway, sans-serif;
неверный шрифт

2023-11-09 15:55 UTC, maryshekk commented on code/src/styles.css
>    font-family: Raleway, sans-serif;
поправить в остальных местах

2023-11-09 15:55 UTC, maryshekk commented on code/src/app/components/product-card/product-card.component.html
> +          <img src="../../../assets/buttons/search-logo.png" [hidden]="!item.recipeOnly">
просто assets тоже работает

2023-11-09 18:10 UTC, jekasrs commented on code/src/app/components/product-card/product-card.component.html
> +          <img src="../../../assets/buttons/search-logo.png" [hidden]="!item.recipeOnly">
Неплохо)

2023-11-09 18:10 UTC, jekasrs commented on code/src/app/components/product-card/product-card.component.html
> +          <img src="../../../assets/buttons/search-logo.png" [hidden]="!item.recipeOnly">
Это я проверял на внимательность :)

2023-11-11 01:00 UTC, mikhaillevashov commented on code/src/app/components/product-card/product-card.component.html
> +        <img id="pharmacies__close-form__button" src="../../../assets/buttons/close.png">
Здесь тоже просто assets тоже работает

2023-11-11 01:08 UTC, mikhaillevashov commented on code/src/app/components/product-card/product-card.component.css
> +.product-card__main {
Давайте определимся, в названиях классов мы будем использовать двойные "пунктир" и "подчеркивание" или же одинарные? Потому что использование то одних, то других мне не понятно

2023-11-11 17:30 UTC, jekasrs commented on code/src/app/components/product-card/product-card.component.css
> +.product-card__main {
На след созвоне ты делаешь презентацию на эту тему: сss: BEM конвенция

https://habr.com/ru/companies/ruvds/articles/347194/

2023-11-11 17:31 UTC, jekasrs commented on code/src/app/components/product-card/product-card.component.html
> +        <img id="pharmacies__close-form__button" src="../../../assets/buttons/close.png">
Исправил.

2023-11-11 17:32 UTC, jekasrs commented on code/src/app/components/product-card/product-card.component.html
> +          <img src="../../../assets/buttons/search-logo.png" [hidden]="!item.recipeOnly">
Исправил.

2023-11-11 17:53 UTC, jekasrs commented on code/src/styles.css
>    font-family: Raleway, sans-serif;
Исправил везде!

2023-11-11 18:20 UTC, jekasrs commented on code/src/app/components/product-card/product-card.component.css
>  }
margin-left: 340px; - не надо использовать для главного элемента компоненты. 

в app.component в стиль нужно прописать: 
.body {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  margin: 0;
}

Тогда все элементы буду центрированы и верстка будет более гибкой.

2023-11-14 18:34 UTC, mikhaillevashov reviewed
.

2023-11-14 18:36 UTC, mikhaillevashov approved these changes
Все хорошо

2023-11-14 18:38 UTC, maryshekk approved these changes

2023-11-14 18:39 UTC, merged