Pharmacist page made up 1.0
jekasrs/online-pharmacy-client pull request #9
Opened 2023-11-05 23:16 UTC by jekasrs

Made all the elements described in the design, except for warnings. First version, useful for further testing.

<img width="1356" alt="Снимок экрана 2023-11-06 в 00 16 30" src="https://github.com/jekasrs/online-pharmacy-client/assets/90210620/edecdf00-539c-4316-996d-aa7759357db3">

2023-11-09 15:48 UTC, maryshekk requested changes

2023-11-09 15:48 UTC, maryshekk commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +}
чекбокс отображается некорректно - некастомный чекбокс следует скрыть:
![image](https://github.com/jekasrs/online-pharmacy-client/assets/106404275/54a8058e-24ac-4c72-9401-0d1b40dd43ab)
посмотри реализацию в cart-page:
![image](https://github.com/jekasrs/online-pharmacy-client/assets/106404275/c8261c1a-a63a-4daf-bbbc-53c9bb99695f)

2023-11-09 15:48 UTC, maryshekk commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +}
не указан шрифт проекта:
![image](https://github.com/jekasrs/online-pharmacy-client/assets/106404275/4bd2e063-2741-4405-b1f9-68c68d14ad52)
для элемента стоит настроить кастомные стили, пусть выпадающий список не соответстует макету, но пусть выглядит хотя бы адекватно

2023-11-09 15:48 UTC, maryshekk commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +}
нет отступа от верхнего края - контейнер с элементами начинается ниже, давай придерживаться единых правил верстки страницы

2023-11-11 02:05 UTC, mikhaillevashov commented on code/src/app/components/pharmacist-page/pharmacist-page.component.html
> +        <label class="search-text upload-image__text" for="image-upload">Размер изображения не превышает 5 Мб</label>
<img width="253" alt="Снимок экрана 2023-11-11 в 05 02 29" src="https://github.com/jekasrs/online-pharmacy-client/assets/108690016/0cf55b8d-a283-4de6-b5f5-f67af43b5033">
Надо бы сделать нормальный отступ от иконки

2023-11-11 02:07 UTC, mikhaillevashov commented on code/src/app/components/pharmacist-page/pharmacist-page.component.html
> +        <img src="assets/pictures/arrow-up.png" (click)="toggleList()">
<img width="257" alt="Снимок экрана 2023-11-11 в 05 01 34" src="https://github.com/jekasrs/online-pharmacy-client/assets/108690016/13a3d873-43cb-45b8-baf6-ff1d163b430e">
Сделать нормальное расположение стрелки

2023-11-11 02:09 UTC, mikhaillevashov commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +.form-editor__left {
Давайте определимся, в названиях классов мы будем использовать двойные "пунктир" и "подчеркивание" или же одинарные? Потому что использование то одних, то других мне не понятно

2023-11-11 19:03 UTC, jekasrs commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +}
Сделал

2023-11-11 19:05 UTC, jekasrs commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +}
margin-top: 170px;
Сделал

2023-11-11 21:40 UTC, jekasrs commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +}
Сделал

2023-11-11 21:43 UTC, jekasrs commented on code/src/app/components/pharmacist-page/pharmacist-page.component.html
> +        <img src="assets/pictures/arrow-up.png" (click)="toggleList()">
Сделал

2023-11-11 21:43 UTC, jekasrs commented on code/src/app/components/pharmacist-page/pharmacist-page.component.css
> +.form-editor__left {
На след созвоне ты делаешь презентацию на эту тему: сss: BEM конвенция

https://habr.com/ru/companies/ruvds/articles/347194/

2023-11-14 18:39 UTC, mikhaillevashov approved these changes

2023-11-14 18:46 UTC, maryshekk approved these changes

2023-11-14 18:48 UTC, merged